# Generated by Django 5.0.6 on 2024-06-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('comments', models.FileField(upload_to='')),
                ('related_products', models.ManyToManyField(blank=True, to='mysite.product')),
            ],
        ),
    ]
